version: '3.8'

services:
  flask-app:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: flask-lab-project
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=false
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
